name: 'dbt_bch_pipeline'
version: '1.0.0'
config-version: 2

profile: 'dbt_bch_pipeline'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_bch_pipeline:
    staging:
      +materialized: table
      +schema: bch_staging
    marts:
      +materialized: table
      +schema: bch_mart